name: Build and Deploy

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Deploy🚀
        run: npm run deploy
